Repository three-ping/MUDIUM_Backend, pull requests merged in 2024-10, with the labels that each got.

#2 feat: 자유게시판 조회기능 추가
  MUDIUM/src/main/java/com/threeping/mudium/board/aggregate/entity/ActiveStatus.java
  MUDIUM/src/main/java/com/threeping/mudium/board/aggregate/entity/Board.java
  MUDIUM/src/main/java/com/threeping/mudium/board/controller/BoardController.java
  MUDIUM/src/main/java/com/threeping/mudium/board/dto/BoardDetailDTO.java
  MUDIUM/src/main/java/com/threeping/mudium/board/dto/BoardListDTO.java
  MUDIUM/src/main/java/com/threeping/mudium/board/repository/BoardRepository.java
  MUDIUM/src/main/java/com/threeping/mudium/board/service/BoardService.java
  MUDIUM/src/main/java/com/threeping/mudium/board/service/BoardServiceImpl.java
  MUDIUM/src/main/java/com/threeping/mudium/common/exception/ErrorCode.java
  MUDIUM/src/test/java/com/threeping/mudium/board/service/BoardServiceImplTests.java
Labels: enhancement

#6 Feature/musical
  MUDIUM/src/main/java/com/threeping/mudium/MudiumApplication.java
  MUDIUM/src/main/java/com/threeping/mudium/common/exception/ErrorCode.java
  MUDIUM/src/main/java/com/threeping/mudium/config/RestTemplateConfig.java
  MUDIUM/src/main/java/com/threeping/mudium/musical/aggregate/Musical.java
  MUDIUM/src/main/java/com/threeping/mudium/musical/controller/MusicalController.java
  MUDIUM/src/main/java/com/threeping/mudium/musical/dto/MusicalItem.java
  MUDIUM/src/main/java/com/threeping/mudium/musical/dto/MusicalListResponse.java
  MUDIUM/src/main/java/com/threeping/mudium/musical/repository/MusicalRepository.java
  MUDIUM/src/main/java/com/threeping/mudium/musical/service/APIService.java
  MUDIUM/src/main/java/com/threeping/mudium/musical/service/APIServiceImpl.java
  MUDIUM/src/main/java/com/threeping/mudium/musical/service/JAXBManager.java
  MUDIUM/src/main/java/com/threeping/mudium/musical/service/MusicalAPIClient.java
  MUDIUM/src/main/java/com/threeping/mudium/musical/service/MusicalService.java
  MUDIUM/src/main/java/com/threeping/mudium/musical/service/MusicalServiceImpl.java
  MUDIUM/src/main/java/com/threeping/mudium/performance/aggregate/Performance.java
  MUDIUM/src/main/java/com/threeping/mudium/performance/dto/PerformanceItem.java
  MUDIUM/src/main/java/com/threeping/mudium/performance/dto/PerformanceResponse.java
  MUDIUM/src/main/java/com/threeping/mudium/performance/repository/PerformanceRepository.java
Labels: enhancement

#8 refactor: common 오류 핸들러 수정
  MUDIUM/src/main/java/com/threeping/mudium/common/exception/GlobalExceptionHandler.java
  MUDIUM/src/main/java/com/threeping/mudium/musical/service/APIServiceImpl.java
Labels: BackEnd🔙

#9 Feature [가이드북] 입문 작품 추천 작성 기능
  .idea/workspace.xml
  MUDIUM/build.gradle
  MUDIUM/src/main/java/com/threeping/mudium/common/exception/ErrorCode.java
  MUDIUM/src/main/java/com/threeping/mudium/guidebook/controller/RecommendedController.java
  MUDIUM/src/main/java/com/threeping/mudium/guidebook/dto/request/RecommendedRequestDTO.java
  MUDIUM/src/main/java/com/threeping/mudium/guidebook/dto/response/RecommendedResponseDTO.java
  MUDIUM/src/main/java/com/threeping/mudium/guidebook/entity/Etiquette.java
  MUDIUM/src/main/java/com/threeping/mudium/guidebook/entity/RecommendedMusical.java
  MUDIUM/src/main/java/com/threeping/mudium/guidebook/repository/RecommendedRepository.java
  MUDIUM/src/main/java/com/threeping/mudium/guidebook/service/RecommendedService.java
  MUDIUM/src/main/java/com/threeping/mudium/guidebook/service/RecommendedServiceImpl.java
  MUDIUM/src/test/java/com/threeping/mudium/guidebook/service/RecommendedServiceTests.java
Labels: feat✨, BackEnd🔙

#13 feat: 리뷰 전체 조회 기능 개발
  MUDIUM/src/main/java/com/threeping/mudium/review/aggregate/dto/ReviewRequestDTO.java
  MUDIUM/src/main/java/com/threeping/mudium/review/aggregate/dto/ReviewResponseDTO.java
  MUDIUM/src/main/java/com/threeping/mudium/review/aggregate/entity/ActiveStatus.java
  MUDIUM/src/main/java/com/threeping/mudium/review/aggregate/entity/Review.java
  MUDIUM/src/main/java/com/threeping/mudium/review/config/AppConfig.java
  MUDIUM/src/main/java/com/threeping/mudium/review/controller/ReviewController.java
  MUDIUM/src/main/java/com/threeping/mudium/review/repository/ReviewRepository.java
  MUDIUM/src/main/java/com/threeping/mudium/review/service/ReviewService.java
  MUDIUM/src/main/java/com/threeping/mudium/review/service/ReviewServiceImpl.java
  MUDIUM/src/test/java/com/threeping/mudium/review/service/ReviewServiceTests.java
Labels: feat✨, BackEnd🔙

#14 ADD: 뮤지컬 상세 정보 조회
  MUDIUM/src/main/java/com/threeping/mudium/common/exception/ErrorCode.java
  MUDIUM/src/main/java/com/threeping/mudium/guidebook/controller/RecommendedController.java
  MUDIUM/src/main/java/com/threeping/mudium/guidebook/dto/request/RecommendedRequestDTO.java
  MUDIUM/src/main/java/com/threeping/mudium/guidebook/dto/response/RecommendedResponseDTO.java
  MUDIUM/src/main/java/com/threeping/mudium/musical/controller/MusicalController.java
  MUDIUM/src/main/java/com/threeping/mudium/musical/dto/MusicalTotalDTO.java
  MUDIUM/src/main/java/com/threeping/mudium/musical/repository/MusicalRepository.java
  MUDIUM/src/main/java/com/threeping/mudium/musical/service/APIServiceImpl.java
  MUDIUM/src/main/java/com/threeping/mudium/musical/service/MusicalAPIClient.java
  MUDIUM/src/main/java/com/threeping/mudium/musical/service/MusicalService.java
  MUDIUM/src/main/java/com/threeping/mudium/musical/service/MusicalServiceImpl.java
  MUDIUM/src/main/java/com/threeping/mudium/performance/aggregate/Performance.java
  MUDIUM/src/main/java/com/threeping/mudium/performance/dto/PerformanceDTO.java
  MUDIUM/src/main/java/com/threeping/mudium/performance/repository/PerformanceRepository.java
  MUDIUM/src/main/java/com/threeping/mudium/performance/service/PerformanceService.java
  MUDIUM/src/main/java/com/threeping/mudium/performance/service/PerformanceServiceImpl.java
  MUDIUM/src/test/java/com/threeping/mudium/guidebook/service/RecommendedServiceTests.java
  MUDIUM/src/test/java/com/threeping/mudium/musical/service/MusicalServiceImplTests.java
Labels: feat✨, BackEnd🔙

#16 feat: 별점 생성&수정&삭제 개발
  .idea/MUDIUM_Backend.iml
  .idea/gradle.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/workspace.xml
  MUDIUM/src/main/java/com/threeping/mudium/scope/aggregate/entity/ScopeEntity.java
  MUDIUM/src/main/java/com/threeping/mudium/scope/aggregate/entity/ScopeId.java
  MUDIUM/src/main/java/com/threeping/mudium/scope/controller/ScopeController.java
  MUDIUM/src/main/java/com/threeping/mudium/scope/repository/ScopeRepository.java
  MUDIUM/src/main/java/com/threeping/mudium/scope/service/ScopeService.java
  MUDIUM/src/main/java/com/threeping/mudium/scope/service/ScopeServiceImpl.java
  MUDIUM/src/test/java/com/threeping/mudium/scope/service/ScopeServiceImplTests.java
Labels: feat✨, BackEnd🔙

#17 feat: 입문 작품 추천 조회 기능
  MUDIUM/src/main/java/com/threeping/mudium/common/ResponseDTO.java
  MUDIUM/src/main/java/com/threeping/mudium/guidebook/controller/RecommendedController.java
  MUDIUM/src/main/java/com/threeping/mudium/guidebook/dto/response/RecommendedResponseDTO.java
  MUDIUM/src/main/java/com/threeping/mudium/guidebook/entity/RecommendedMusical.java
  MUDIUM/src/main/java/com/threeping/mudium/guidebook/service/RecommendedService.java
  MUDIUM/src/main/java/com/threeping/mudium/guidebook/service/RecommendedServiceImpl.java
  MUDIUM/src/test/java/com/threeping/mudium/guidebook/service/RecommendedServiceTests.java
Labels: feat✨, BackEnd🔙

#26 feat: 관람매너 CRUD 기능
  MUDIUM/src/main/java/com/threeping/mudium/guidebook/controller/EtiquetteController.java
  MUDIUM/src/main/java/com/threeping/mudium/guidebook/controller/RecommendedController.java
  MUDIUM/src/main/java/com/threeping/mudium/guidebook/dto/EtiquetteRequestDTO.java
  MUDIUM/src/main/java/com/threeping/mudium/guidebook/dto/RecommendedRequestDTO.java
  MUDIUM/src/main/java/com/threeping/mudium/guidebook/entity/Etiquette.java
  MUDIUM/src/main/java/com/threeping/mudium/guidebook/repository/EtiquetteRepository.java
  MUDIUM/src/main/java/com/threeping/mudium/guidebook/service/ettiquette/EtiquetteService.java
  MUDIUM/src/main/java/com/threeping/mudium/guidebook/service/ettiquette/EtiquetteServiceImpl.java
  MUDIUM/src/main/java/com/threeping/mudium/guidebook/service/recommendedMusical/RecommendedService.java
  MUDIUM/src/main/java/com/threeping/mudium/guidebook/service/recommendedMusical/RecommendedServiceImpl.java
  MUDIUM/src/test/java/com/threeping/mudium/guidebook/service/RecommendedServiceTests.java
Labels: feat✨, BackEnd🔙

#27 feat: 기본 및 회원별 커스텀 티켓 생성&수정&삭제 개발
  MUDIUM/src/main/java/com/threeping/mudium/customticket/aggregate/dto/CustomTicketDTO.java
  MUDIUM/src/main/java/com/threeping/mudium/customticket/aggregate/dto/UserCustomTicketDTO.java
  MUDIUM/src/main/java/com/threeping/mudium/customticket/aggregate/entity/CustomTicketEntity.java
  MUDIUM/src/main/java/com/threeping/mudium/customticket/aggregate/entity/UserCustomTicketEntity.java
  MUDIUM/src/main/java/com/threeping/mudium/customticket/aggregate/entity/UserCustomTicketId.java
  MUDIUM/src/main/java/com/threeping/mudium/customticket/controller/CustomTicketController.java
  MUDIUM/src/main/java/com/threeping/mudium/customticket/controller/UserCustomTicketController.java
  MUDIUM/src/main/java/com/threeping/mudium/customticket/repository/CustomTicketRepository.java
  MUDIUM/src/main/java/com/threeping/mudium/customticket/repository/UserCustomTicketRepository.java
  MUDIUM/src/main/java/com/threeping/mudium/customticket/service/CustomTicketService.java
  MUDIUM/src/main/java/com/threeping/mudium/customticket/service/CustomTicketServiceImpl.java
  MUDIUM/src/main/java/com/threeping/mudium/customticket/service/UserCustomTicketService.java
  MUDIUM/src/main/java/com/threeping/mudium/customticket/service/UserCustomTicketServiceImpl.java
  MUDIUM/src/test/java/com/threeping/mudium/customticket/service/CustomTicketServiceImplTests.java
  MUDIUM/src/test/java/com/threeping/mudium/customticket/service/UserCustomTicketServiceImplTests.java
Labels: feat✨, BackEnd🔙

#32 feat: 리뷰 상세 조회 기능 개발
  MUDIUM/src/main/java/com/threeping/mudium/review/controller/ReviewController.java
  MUDIUM/src/main/java/com/threeping/mudium/review/repository/ReviewRepository.java
  MUDIUM/src/main/java/com/threeping/mudium/review/service/ReviewService.java
  MUDIUM/src/main/java/com/threeping/mudium/review/service/ReviewServiceImpl.java
  MUDIUM/src/test/java/com/threeping/mudium/review/service/ReviewServiceTests.java
Labels: feat✨, BackEnd🔙

#36 refactor: 주석 제거
  MUDIUM/src/main/java/com/threeping/mudium/customticket/controller/CustomTicketController.java
  MUDIUM/src/main/java/com/threeping/mudium/customticket/controller/UserCustomTicketController.java
  MUDIUM/src/main/java/com/threeping/mudium/customticket/service/CustomTicketService.java
  MUDIUM/src/main/java/com/threeping/mudium/customticket/service/CustomTicketServiceImpl.java
  MUDIUM/src/test/java/com/threeping/mudium/customticket/service/CustomTicketServiceImplTests.java
  MUDIUM/src/test/java/com/threeping/mudium/customticket/service/UserCustomTicketServiceImplTests.java
Labels: refactor✂️

#38 ADD: 뮤지컬 게시판 조회
  MUDIUM/src/main/java/com/threeping/mudium/common/exception/ErrorCode.java
  MUDIUM/src/main/java/com/threeping/mudium/musical/controller/MusicalController.java
  MUDIUM/src/main/java/com/threeping/mudium/musical/service/MusicalService.java
  MUDIUM/src/main/java/com/threeping/mudium/musical/service/MusicalServiceImpl.java
  MUDIUM/src/main/java/com/threeping/mudium/musicalboard/aggregate/ActiveStatus.java
  MUDIUM/src/main/java/com/threeping/mudium/musicalboard/aggregate/MusicalPost.java
  MUDIUM/src/main/java/com/threeping/mudium/musicalboard/controller/MusicalBoardController.java
  MUDIUM/src/main/java/com/threeping/mudium/musicalboard/dto/MusicalPostDTO.java
  MUDIUM/src/main/java/com/threeping/mudium/musicalboard/dto/MusicalPostListDTO.java
  MUDIUM/src/main/java/com/threeping/mudium/musicalboard/repository/MusicalBoardRepository.java
  MUDIUM/src/main/java/com/threeping/mudium/musicalboard/service/MusicalBoardService.java
  MUDIUM/src/main/java/com/threeping/mudium/musicalboard/service/MusicalBoardServiceImpl.java
  MUDIUM/src/test/java/com/threeping/mudium/musical/service/MusicalServiceImplTests.java
  MUDIUM/src/test/java/com/threeping/mudium/musicalboard/service/MusicalBoardServiceImplTests.java
Labels: feat✨, BackEnd🔙

#41 [자유게시글] 자유게시글 작성 기능 추가
  MUDIUM/src/main/java/com/threeping/mudium/board/aggregate/entity/Board.java
  MUDIUM/src/main/java/com/threeping/mudium/board/controller/BoardController.java
  MUDIUM/src/main/java/com/threeping/mudium/board/dto/RegistBoardDTO.java
  MUDIUM/src/main/java/com/threeping/mudium/board/service/BoardService.java
  MUDIUM/src/main/java/com/threeping/mudium/board/service/BoardServiceImpl.java
  MUDIUM/src/test/java/com/threeping/mudium/board/service/BoardServiceImplTests.java
Labels: feat✨, BackEnd🔙

#42 feat: 리뷰 작성 기능 개발
  MUDIUM/src/main/java/com/threeping/mudium/common/exception/ErrorCode.java
  MUDIUM/src/main/java/com/threeping/mudium/review/aggregate/dto/ReviewRequestDTO.java
  MUDIUM/src/main/java/com/threeping/mudium/review/aggregate/dto/ReviewResponseDTO.java
  MUDIUM/src/main/java/com/threeping/mudium/review/aggregate/entity/Review.java
  MUDIUM/src/main/java/com/threeping/mudium/review/controller/ReviewController.java
  MUDIUM/src/main/java/com/threeping/mudium/review/service/ReviewService.java
  MUDIUM/src/main/java/com/threeping/mudium/review/service/ReviewServiceImpl.java
  MUDIUM/src/test/java/com/threeping/mudium/review/service/ReviewServiceTests.java
Labels: feat✨, BackEnd🔙

#44 [feat] userId로 유저 조회 API
  Assets/Calendar/image (1).png
  Assets/Calendar/image (2).png
  Assets/Calendar/image (3).png
  Assets/Calendar/image (4).png
  Assets/Ticket/image (10).png
  Assets/Ticket/image (5).png
  Assets/Ticket/image (7).png
  Assets/Ticket/image (9).png
  MUDIUM/build.gradle
  MUDIUM/src/main/java/com/threeping/mudium/board/controller/BoardController.java
  MUDIUM/src/main/java/com/threeping/mudium/common/exception/ErrorCode.java
  MUDIUM/src/main/java/com/threeping/mudium/config/AppConfiguration.java
  MUDIUM/src/main/java/com/threeping/mudium/musical/controller/MusicalController.java
  MUDIUM/src/main/java/com/threeping/mudium/musicalboard/controller/MusicalBoardController.java
  MUDIUM/src/main/java/com/threeping/mudium/user/aggregate/dto/UserDTO.java
  MUDIUM/src/main/java/com/threeping/mudium/user/aggregate/entity/UserEntity.java
  MUDIUM/src/main/java/com/threeping/mudium/user/aggregate/entity/UserRole.java
  MUDIUM/src/main/java/com/threeping/mudium/user/aggregate/vo/OAuth2LoginVO.java
  MUDIUM/src/main/java/com/threeping/mudium/user/aggregate/vo/RequestLoginVO.java
  MUDIUM/src/main/java/com/threeping/mudium/user/aggregate/vo/RequestRegistUserVO.java
  MUDIUM/src/main/java/com/threeping/mudium/user/aggregate/vo/ResponseUserVO.java
  MUDIUM/src/main/java/com/threeping/mudium/user/aggregate/vo/login/ResponseNormalLoginVO.java
  MUDIUM/src/main/java/com/threeping/mudium/user/config/AppConfig.java
  MUDIUM/src/main/java/com/threeping/mudium/user/config/RedisConfig.java
  MUDIUM/src/main/java/com/threeping/mudium/user/controller/OAuth2Controller.java
  MUDIUM/src/main/java/com/threeping/mudium/user/controller/UserController.java
  MUDIUM/src/main/java/com/threeping/mudium/user/repository/UserRepository.java
  MUDIUM/src/main/java/com/threeping/mudium/user/security/AuthenticationFilter.java
  MUDIUM/src/main/java/com/threeping/mudium/user/security/CustomAuthenticationFailureHandler.java
  MUDIUM/src/main/java/com/threeping/mudium/user/security/JwtFilter.java
  MUDIUM/src/main/java/com/threeping/mudium/user/security/JwtUtil.java
  MUDIUM/src/main/java/com/threeping/mudium/user/security/WebSecurity.java
  MUDIUM/src/main/java/com/threeping/mudium/user/service/EmailVerificationService.java
  MUDIUM/src/main/java/com/threeping/mudium/user/service/OAuth2UserService.java
  MUDIUM/src/main/java/com/threeping/mudium/user/service/OAuth2UserServiceImpl.java
  MUDIUM/src/main/java/com/threeping/mudium/user/service/UserService.java
  MUDIUM/src/main/java/com/threeping/mudium/user/service/UserServiceImpl.java
Labels: BackEnd🔙

#46 feat: 리뷰 수정 기능 개발
  MUDIUM/src/main/java/com/threeping/mudium/review/controller/ReviewController.java
  MUDIUM/src/main/java/com/threeping/mudium/review/service/ReviewService.java
  MUDIUM/src/main/java/com/threeping/mudium/review/service/ReviewServiceImpl.java
  MUDIUM/src/test/java/com/threeping/mudium/review/service/ReviewServiceTests.java
Labels: feat✨, BackEnd🔙

#47 feat: 리뷰 삭제 기능 개발
  MUDIUM/src/main/java/com/threeping/mudium/common/exception/ErrorCode.java
  MUDIUM/src/main/java/com/threeping/mudium/review/controller/ReviewController.java
  MUDIUM/src/main/java/com/threeping/mudium/review/repository/ReviewRepository.java
  MUDIUM/src/main/java/com/threeping/mudium/review/service/ReviewService.java
  MUDIUM/src/main/java/com/threeping/mudium/review/service/ReviewServiceImpl.java
  MUDIUM/src/test/java/com/threeping/mudium/review/service/ReviewServiceTests.java
Labels: feat✨, BackEnd🔙

#48 [자유게시글] 게시글 수정,삭제 기능 추가
  MUDIUM/src/main/java/com/threeping/mudium/board/controller/BoardController.java
  MUDIUM/src/main/java/com/threeping/mudium/board/dto/BoardListDTO.java
  MUDIUM/src/main/java/com/threeping/mudium/board/dto/UpdateBoardDTO.java
  MUDIUM/src/main/java/com/threeping/mudium/board/repository/BoardRepository.java
  MUDIUM/src/main/java/com/threeping/mudium/board/service/BoardService.java
  MUDIUM/src/main/java/com/threeping/mudium/board/service/BoardServiceImpl.java
  MUDIUM/src/main/java/com/threeping/mudium/common/exception/ErrorCode.java
  MUDIUM/src/test/java/com/threeping/mudium/board/service/BoardServiceImplTests.java
Labels: feat✨, BackEnd🔙

#49 feat: 회원별 커스텀 티켓 조회
  MUDIUM/src/main/java/com/threeping/mudium/customticket/controller/UserCustomTicketController.java
  MUDIUM/src/main/java/com/threeping/mudium/customticket/repository/UserCustomTicketRepository.java
  MUDIUM/src/main/java/com/threeping/mudium/customticket/service/UserCustomTicketService.java
  MUDIUM/src/main/java/com/threeping/mudium/customticket/service/UserCustomTicketServiceImpl.java
Labels: feat✨, BackEnd🔙

#57 ADD: 뮤지컬 검색을 통한 동적 조회, 뮤지컬 조회 시, 평균 별점 조회
  MUDIUM/src/main/java/com/threeping/mudium/common/exception/ErrorCode.java
  MUDIUM/src/main/java/com/threeping/mudium/musical/aggregate/Musical.java
  MUDIUM/src/main/java/com/threeping/mudium/musical/controller/MusicalController.java
  MUDIUM/src/main/java/com/threeping/mudium/musical/dto/MusicalListDTO.java
  MUDIUM/src/main/java/com/threeping/mudium/musical/dto/MusicalTotalDTO.java
  MUDIUM/src/main/java/com/threeping/mudium/musical/repository/MusicalRepository.java
  MUDIUM/src/main/java/com/threeping/mudium/musical/service/APIServiceImpl.java
  MUDIUM/src/main/java/com/threeping/mudium/musical/service/MusicalAPIClient.java
  MUDIUM/src/main/java/com/threeping/mudium/musical/service/MusicalService.java
  MUDIUM/src/main/java/com/threeping/mudium/musical/service/MusicalServiceImpl.java
  MUDIUM/src/main/java/com/threeping/mudium/performance/aggregate/Performance.java
  MUDIUM/src/main/java/com/threeping/mudium/performance/dto/PerformanceItem.java
  MUDIUM/src/main/java/com/threeping/mudium/scope/aggregate/entity/ScopeEntity.java
  MUDIUM/src/main/java/com/threeping/mudium/scope/aggregate/entity/ScopeId.java
  MUDIUM/src/main/java/com/threeping/mudium/scope/controller/ScopeController.java
  MUDIUM/src/main/java/com/threeping/mudium/scope/dto/ScopeDTO.java
  MUDIUM/src/main/java/com/threeping/mudium/scope/repository/ScopeRepository.java
  MUDIUM/src/main/java/com/threeping/mudium/scope/service/ScopeService.java
  MUDIUM/src/main/java/com/threeping/mudium/scope/service/ScopeServiceImpl.java
  MUDIUM/src/main/java/com/threeping/mudium/scope/vo/ScopeVO.java
  MUDIUM/src/test/java/com/threeping/mudium/customticket/service/CustomTicketServiceImplTests.java
  MUDIUM/src/test/java/com/threeping/mudium/musical/service/MusicalServiceImplTests.java
  MUDIUM/src/test/java/com/threeping/mudium/scope/service/ScopeServiceImplTests.java
Labels: feat✨, BackEnd🔙

#58 [자유게시글] 자유게시글 검색 기능 추가
  MUDIUM/src/main/java/com/threeping/mudium/board/controller/BoardController.java
  MUDIUM/src/main/java/com/threeping/mudium/board/repository/BoardRepository.java
  MUDIUM/src/main/java/com/threeping/mudium/board/service/BoardService.java
  MUDIUM/src/main/java/com/threeping/mudium/board/service/BoardServiceImpl.java
Labels: feat✨, BackEnd🔙

#61 feat: 커스텀 티켓 조회
  MUDIUM/src/main/java/com/threeping/mudium/customticket/controller/CustomTicketController.java
  MUDIUM/src/main/java/com/threeping/mudium/customticket/service/CustomTicketService.java
  MUDIUM/src/main/java/com/threeping/mudium/customticket/service/CustomTicketServiceImpl.java
Labels: feat✨, BackEnd🔙

#62 feat: 비밀리뷰 CUD 기능 개발
  MUDIUM/src/main/java/com/threeping/mudium/secretreview/controller/SecretReviewController.java
  MUDIUM/src/main/java/com/threeping/mudium/secretreview/service/SecretReviewService.java
  MUDIUM/src/main/java/com/threeping/mudium/secretreview/service/SecretReviewServiceImpl.java
  MUDIUM/src/test/java/com/threeping/mudium/secretreview/service/SecretReviewServiceTests.java
Labels: feat✨, BackEnd🔙

#67 [가이드북] bookmark CRD 기능 구현
  MUDIUM/src/main/java/com/threeping/mudium/bookmark/controller/BookmarkController.java
  MUDIUM/src/main/java/com/threeping/mudium/bookmark/dto/BookmarkRequestDTO.java
  MUDIUM/src/main/java/com/threeping/mudium/bookmark/dto/BookmarkResponseDTO.java
  MUDIUM/src/main/java/com/threeping/mudium/bookmark/entity/Bookmark.java
  MUDIUM/src/main/java/com/threeping/mudium/bookmark/entity/BookmarkPK.java
  MUDIUM/src/main/java/com/threeping/mudium/bookmark/repository/BookmarkRepository.java
  MUDIUM/src/main/java/com/threeping/mudium/bookmark/service/BookmarkService.java
  MUDIUM/src/main/java/com/threeping/mudium/bookmark/service/BookmarkServiceImpl.java
  MUDIUM/src/main/java/com/threeping/mudium/common/exception/GlobalExceptionHandler.java
  MUDIUM/src/main/java/com/threeping/mudium/musical/aggregate/Musical.java
  MUDIUM/src/main/java/com/threeping/mudium/user/aggregate/entity/UserEntity.java
Labels: feat✨, BackEnd🔙

#71 [공지게시글] 공지게시글 작성 기능 추가
  MUDIUM/src/main/java/com/threeping/mudium/board/aggregate/entity/Board.java
  MUDIUM/src/main/java/com/threeping/mudium/board/controller/BoardController.java
  MUDIUM/src/main/java/com/threeping/mudium/board/dto/BoardDetailDTO.java
  MUDIUM/src/main/java/com/threeping/mudium/board/dto/BoardListDTO.java
  MUDIUM/src/main/java/com/threeping/mudium/board/dto/UpdateBoardDTO.java
  MUDIUM/src/main/java/com/threeping/mudium/board/service/BoardService.java
  MUDIUM/src/main/java/com/threeping/mudium/board/service/BoardServiceImpl.java
  MUDIUM/src/main/java/com/threeping/mudium/common/exception/ErrorCode.java
  MUDIUM/src/main/java/com/threeping/mudium/notice/controller/NoticeController.java
  MUDIUM/src/main/java/com/threeping/mudium/notice/dto/CreateNoticeDTO.java
  MUDIUM/src/main/java/com/threeping/mudium/notice/service/NoticeService.java
  MUDIUM/src/main/java/com/threeping/mudium/notice/service/NoticeServiceImpl.java
  MUDIUM/src/test/java/com/threeping/mudium/board/service/BoardServiceImplTests.java
  MUDIUM/src/test/java/com/threeping/mudium/notice/service/NoticeServiceImplTests.java
Labels: feat✨, BackEnd🔙

#73 ADD: 뮤지컬 게시판 대댓글 조회 기능
  .gitignore
  MUDIUM/src/main/java/com/threeping/mudium/common/exception/ErrorCode.java
  MUDIUM/src/main/java/com/threeping/mudium/mucialcomment/aggregate/ActiveStatus.java
  MUDIUM/src/main/java/com/threeping/mudium/mucialcomment/aggregate/MusicalComment.java
  MUDIUM/src/main/java/com/threeping/mudium/mucialcomment/controller/MusicalCommentController.java
  MUDIUM/src/main/java/com/threeping/mudium/mucialcomment/dto/MusicalCommentDTO.java
  MUDIUM/src/main/java/com/threeping/mudium/mucialcomment/repository/MusicalCommentRepository.java
  MUDIUM/src/main/java/com/threeping/mudium/mucialcomment/service/MusicalCommentService.java
  MUDIUM/src/main/java/com/threeping/mudium/mucialcomment/service/MusicalCommentServiceImpl.java
  MUDIUM/src/main/java/com/threeping/mudium/mucialcomment/vo/MusicalCommentVO.java
  MUDIUM/src/main/java/com/threeping/mudium/musicalboard/aggregate/MusicalPost.java
  MUDIUM/src/main/java/com/threeping/mudium/musicalboard/aggregate/MusicalReply.java
  MUDIUM/src/main/java/com/threeping/mudium/musicalboard/controller/MusicalBoardController.java
  MUDIUM/src/main/java/com/threeping/mudium/musicalboard/dto/MusicalPostDTO.java
  MUDIUM/src/main/java/com/threeping/mudium/musicalboard/dto/MusicalPostListDTO.java
  MUDIUM/src/main/java/com/threeping/mudium/musicalboard/repository/MusicalBoardRepository.java
  MUDIUM/src/main/java/com/threeping/mudium/musicalboard/service/MusicalBoardService.java
  MUDIUM/src/main/java/com/threeping/mudium/musicalboard/service/MusicalBoardServiceImpl.java
  MUDIUM/src/main/java/com/threeping/mudium/musicalreply/aggregate/ActiveStatus.java
  MUDIUM/src/main/java/com/threeping/mudium/musicalreply/aggregate/MusicalReply.java
  MUDIUM/src/main/java/com/threeping/mudium/musicalreply/controller/MusicalReplyController.java
  MUDIUM/src/main/java/com/threeping/mudium/musicalreply/dto/MusicalReplyDTO.java
  MUDIUM/src/main/java/com/threeping/mudium/musicalreply/repository/MusicalReplyRepository.java
  MUDIUM/src/main/java/com/threeping/mudium/musicalreply/service/MusicalReplyService.java
  MUDIUM/src/main/java/com/threeping/mudium/musicalreply/service/MusicalReplyServiceImpl.java
  MUDIUM/src/main/java/com/threeping/mudium/musicalreply/vo/MusicalReplyVO.java
  MUDIUM/src/test/java/com/threeping/mudium/mucialcomment/service/MusicalCommentServiceImplTests.java
  MUDIUM/src/test/java/com/threeping/mudium/musicalboard/service/MusicalBoardServiceImplTest.java
  MUDIUM/src/test/java/com/threeping/mudium/musicalboard/service/MusicalBoardServiceImplTests.java
  MUDIUM/src/test/java/com/threeping/mudium/musicalreply/service/MusicalReplyServiceImplTests.java
Labels: feat✨, BackEnd🔙

#74 [공지게시글] 공지게시글 수정 및 삭제 기능 추가
  MUDIUM/src/main/java/com/threeping/mudium/common/exception/ErrorCode.java
  MUDIUM/src/main/java/com/threeping/mudium/notice/controller/NoticeController.java
  MUDIUM/src/main/java/com/threeping/mudium/notice/dto/UpdateNoticeDTO.java
  MUDIUM/src/main/java/com/threeping/mudium/notice/service/NoticeService.java
  MUDIUM/src/main/java/com/threeping/mudium/notice/service/NoticeServiceImpl.java
  MUDIUM/src/test/java/com/threeping/mudium/notice/service/NoticeServiceImplTests.java
Labels: feat✨, BackEnd🔙

#76 [뮤지컬 게시판]ADD: 대댓글 CUD 기능 추가
  MUDIUM/src/main/java/com/threeping/mudium/common/exception/ErrorCode.java
  MUDIUM/src/main/java/com/threeping/mudium/mucialcomment/repository/MusicalCommentRepository.java
  MUDIUM/src/main/java/com/threeping/mudium/mucialcomment/service/MusicalCommentService.java
  MUDIUM/src/main/java/com/threeping/mudium/mucialcomment/service/MusicalCommentServiceImpl.java
  MUDIUM/src/main/java/com/threeping/mudium/musicalboard/aggregate/MusicalPost.java
  MUDIUM/src/main/java/com/threeping/mudium/musicalboard/service/MusicalBoardService.java
  MUDIUM/src/main/java/com/threeping/mudium/musicalboard/service/MusicalBoardServiceImpl.java
  MUDIUM/src/main/java/com/threeping/mudium/musicalreply/aggregate/MusicalReply.java
  MUDIUM/src/main/java/com/threeping/mudium/musicalreply/controller/MusicalReplyController.java
  MUDIUM/src/main/java/com/threeping/mudium/musicalreply/repository/MusicalReplyRepository.java
  MUDIUM/src/main/java/com/threeping/mudium/musicalreply/service/MusicalReplyService.java
  MUDIUM/src/main/java/com/threeping/mudium/musicalreply/service/MusicalReplyServiceImpl.java
  MUDIUM/src/test/java/com/threeping/mudium/musicalreply/service/MusicalReplyServiceImplTests.java
Labels: feat✨, BackEnd🔙

#78 [문의게시글] 문의게시글 조회 기능 추가
  MUDIUM/src/main/java/com/threeping/mudium/common/exception/ErrorCode.java
  MUDIUM/src/main/java/com/threeping/mudium/inquiry/aggregate/entity/Inquiry.java
  MUDIUM/src/main/java/com/threeping/mudium/inquiry/aggregate/enumerate/SearchType.java
  MUDIUM/src/main/java/com/threeping/mudium/inquiry/controller/InquiryController.java
  MUDIUM/src/main/java/com/threeping/mudium/inquiry/dto/InquiryDetailDTO.java
  MUDIUM/src/main/java/com/threeping/mudium/inquiry/dto/InquiryListDTO.java
  MUDIUM/src/main/java/com/threeping/mudium/inquiry/repository/InquiryRepository.java
  MUDIUM/src/main/java/com/threeping/mudium/inquiry/service/InquiryService.java
  MUDIUM/src/main/java/com/threeping/mudium/inquiry/service/InquiryServiceImpl.java
  MUDIUM/src/test/java/com/threeping/mudium/inquiry/service/InquiryServiceImplTests.java
Labels: feat✨, BackEnd🔙

#80 [문의게시글] 문의게시글 등록 기능 추가
  MUDIUM/src/main/java/com/threeping/mudium/inquiry/controller/InquiryController.java
  MUDIUM/src/main/java/com/threeping/mudium/inquiry/dto/CreateInquiryDTO.java
  MUDIUM/src/main/java/com/threeping/mudium/inquiry/service/InquiryService.java
  MUDIUM/src/main/java/com/threeping/mudium/inquiry/service/InquiryServiceImpl.java
  MUDIUM/src/test/java/com/threeping/mudium/inquiry/service/InquiryServiceImplTests.java
Labels: feat✨, BackEnd🔙

#82 [문의게시글] 문의 게시글 수정 및 삭제 기능 추가
  MUDIUM/src/main/java/com/threeping/mudium/inquiry/controller/InquiryController.java
  MUDIUM/src/main/java/com/threeping/mudium/inquiry/dto/UpdateInquiryDTO.java
  MUDIUM/src/main/java/com/threeping/mudium/inquiry/service/InquiryService.java
  MUDIUM/src/main/java/com/threeping/mudium/inquiry/service/InquiryServiceImpl.java
  MUDIUM/src/test/java/com/threeping/mudium/inquiry/service/InquiryServiceImplTests.java
Labels: feat✨, BackEnd🔙

#84 [자유게시글 댓글] 댓글 조회 및 생성 기능 추가
  MUDIUM/src/main/java/com/threeping/mudium/boardcomment/aggregate/BoardComment.java
  MUDIUM/src/main/java/com/threeping/mudium/boardcomment/controller/BoardCommentController.java
  MUDIUM/src/main/java/com/threeping/mudium/boardcomment/dto/BoardCommentDTO.java
  MUDIUM/src/main/java/com/threeping/mudium/boardcomment/repository/BoardCommentRepository.java
  MUDIUM/src/main/java/com/threeping/mudium/boardcomment/service/BoardCommentService.java
  MUDIUM/src/main/java/com/threeping/mudium/boardcomment/service/BoardCommentServiceImpl.java
  MUDIUM/src/test/java/com/threeping/mudium/boardcomment/service/BoardCommentServiceImplTests.java
  MUDIUM/src/test/java/com/threeping/mudium/inquiry/service/InquiryServiceImplTests.java
Labels: feat✨, BackEnd🔙

#86 refactor: 리뷰 전체적인 수정
  MUDIUM/src/main/java/com/threeping/mudium/review/controller/ReviewController.java
  MUDIUM/src/main/java/com/threeping/mudium/review/dto/ReviewResponseDTO.java
  MUDIUM/src/main/java/com/threeping/mudium/review/service/ReviewServiceImpl.java
Labels: BackEnd🔙, refactor✂️, fix🛠️

#88 [자유게시글 댓글] 자유게시글 댓글 수정 및 삭제
  MUDIUM/src/main/java/com/threeping/mudium/boardcomment/controller/BoardCommentController.java
  MUDIUM/src/main/java/com/threeping/mudium/boardcomment/service/BoardCommentService.java
  MUDIUM/src/main/java/com/threeping/mudium/boardcomment/service/BoardCommentServiceImpl.java
  MUDIUM/src/main/java/com/threeping/mudium/common/exception/ErrorCode.java
  MUDIUM/src/test/java/com/threeping/mudium/boardcomment/service/BoardCommentServiceImplTests.java
Labels: feat✨, BackEnd🔙

#90 [자유게시글 대댓글] 자유게시글 대댓글 조회 및 생성 기능 추가
  MUDIUM/src/main/java/com/threeping/mudium/boardreply/aggregate/entity/BoardReply.java
  MUDIUM/src/main/java/com/threeping/mudium/boardreply/controller/BoardReplyController.java
  MUDIUM/src/main/java/com/threeping/mudium/boardreply/dto/BoardReplyDTO.java
  MUDIUM/src/main/java/com/threeping/mudium/boardreply/repository/BoardReplyRepository.java
  MUDIUM/src/main/java/com/threeping/mudium/boardreply/service/BoardReplyService.java
  MUDIUM/src/main/java/com/threeping/mudium/boardreply/service/BoardReplyServiceImpl.java
  MUDIUM/src/test/java/com/threeping/mudium/boardcomment/service/BoardCommentServiceImplTests.java
  MUDIUM/src/test/java/com/threeping/mudium/boardreply/service/BoardReplyServiceImplTests.java
Labels: feat✨, BackEnd🔙

#92 [자유게시글 대댓글] 자유게시글 대댓글 수정 및 삭제 기능 추가
  MUDIUM/src/main/java/com/threeping/mudium/boardreply/controller/BoardReplyController.java
  MUDIUM/src/main/java/com/threeping/mudium/boardreply/repository/BoardReplyRepository.java
  MUDIUM/src/main/java/com/threeping/mudium/boardreply/service/BoardReplyService.java
  MUDIUM/src/main/java/com/threeping/mudium/boardreply/service/BoardReplyServiceImpl.java
  MUDIUM/src/main/java/com/threeping/mudium/common/exception/ErrorCode.java
  MUDIUM/src/test/java/com/threeping/mudium/boardreply/service/BoardReplyServiceImplTests.java
Labels: feat✨, BackEnd🔙

#95 feat: 비밀리뷰 전체적인 수정
  MUDIUM/src/main/java/com/threeping/mudium/secretreview/controller/SecretReviewController.java
  MUDIUM/src/main/java/com/threeping/mudium/secretreview/dto/SecretReviewResponseDTO.java
Labels: BackEnd🔙, refactor✂️, fix🛠️

#96 ADD: 뮤지컬과 공연 정보를 저장하는 API 로직 수정 및 공연 순위를 저장하는 API 기능 추가
  MUDIUM/src/main/java/com/threeping/mudium/common/exception/ErrorCode.java
  MUDIUM/src/main/java/com/threeping/mudium/musical/dto/MusicalDTO.java
  MUDIUM/src/main/java/com/threeping/mudium/musical/service/APIServiceImpl.java
  MUDIUM/src/main/java/com/threeping/mudium/musical/service/JAXBManager.java
  MUDIUM/src/main/java/com/threeping/mudium/musical/service/MusicalAPIClient.java
  MUDIUM/src/main/java/com/threeping/mudium/musical/service/MusicalService.java
  MUDIUM/src/main/java/com/threeping/mudium/musical/service/MusicalServiceImpl.java
  MUDIUM/src/main/java/com/threeping/mudium/performance/aggregate/PerformanceRank.java
  MUDIUM/src/main/java/com/threeping/mudium/performance/aggregate/RankType.java
  MUDIUM/src/main/java/com/threeping/mudium/performance/dto/PerformanceDTO.java
  MUDIUM/src/main/java/com/threeping/mudium/performance/dto/RankItem.java
  MUDIUM/src/main/java/com/threeping/mudium/performance/dto/RankResponse.java
  MUDIUM/src/main/java/com/threeping/mudium/performance/repository/PerformanceRankRepository.java
  MUDIUM/src/main/java/com/threeping/mudium/performance/repository/PerformanceRepository.java
  MUDIUM/src/main/java/com/threeping/mudium/performance/service/PerformanceService.java
  MUDIUM/src/main/java/com/threeping/mudium/performance/service/PerformanceServiceImpl.java
  MUDIUM/src/main/java/com/threeping/mudium/performance/service/RankAPIClient.java
  MUDIUM/src/main/java/com/threeping/mudium/performance/service/RankAPIService.java
  MUDIUM/src/main/java/com/threeping/mudium/performance/service/RankAPIServiceImpl.java
Labels: feat✨, BackEnd🔙, refactor✂️, fix🛠️

#98 ADD: 리뷰 댓글 조회 기능 추가
  MUDIUM/src/main/java/com/threeping/mudium/common/exception/ErrorCode.java
  MUDIUM/src/main/java/com/threeping/mudium/mucialcomment/repository/MusicalCommentRepository.java
  MUDIUM/src/main/java/com/threeping/mudium/mucialcomment/service/MusicalCommentServiceImpl.java
  MUDIUM/src/main/java/com/threeping/mudium/musical/service/APIServiceImpl.java
  MUDIUM/src/main/java/com/threeping/mudium/musicalboardlike/aggregate/MusicalBoardLike.java
  MUDIUM/src/main/java/com/threeping/mudium/musicalboardlike/aggregate/MusicalBoardLikePK.java
  MUDIUM/src/main/java/com/threeping/mudium/musicalboardlike/controller/MusicalBoardLikeController.java
  MUDIUM/src/main/java/com/threeping/mudium/musicalboardlike/repository/MusicalBoardLikeRepository.java
  MUDIUM/src/main/java/com/threeping/mudium/musicalboardlike/service/MusicalBoardLikeService.java
  MUDIUM/src/main/java/com/threeping/mudium/musicalboardlike/service/MusicalBoardLikeServiceImpl.java
  MUDIUM/src/main/java/com/threeping/mudium/performance/service/RankAPIServiceImpl.java
  MUDIUM/src/main/java/com/threeping/mudium/review/controller/ReviewController.java
  MUDIUM/src/main/java/com/threeping/mudium/review/dto/ReviewWithScopeDTO.java
  MUDIUM/src/main/java/com/threeping/mudium/review/repository/ReviewRepository.java
  MUDIUM/src/main/java/com/threeping/mudium/review/service/ReviewService.java
  MUDIUM/src/main/java/com/threeping/mudium/review/service/ReviewServiceImpl.java
  MUDIUM/src/main/java/com/threeping/mudium/reviewcomment/aggregate/ActiveStatus.java
  MUDIUM/src/main/java/com/threeping/mudium/reviewcomment/aggregate/ReviewComment.java
  MUDIUM/src/main/java/com/threeping/mudium/reviewcomment/controller/ReviewCommentController.java
  MUDIUM/src/main/java/com/threeping/mudium/reviewcomment/dto/ReviewCommentDTO.java
  MUDIUM/src/main/java/com/threeping/mudium/reviewcomment/repository/ReviewCommentRepository.java
  MUDIUM/src/main/java/com/threeping/mudium/reviewcomment/service/ReviewCommentService.java
  MUDIUM/src/main/java/com/threeping/mudium/reviewcomment/service/ReviewCommentServiceImpl.java
  MUDIUM/src/main/java/com/threeping/mudium/reviewcomment/vo/ReviewCommentVO.java
  MUDIUM/src/main/java/com/threeping/mudium/scope/aggregate/entity/ScopeEntity.java
  MUDIUM/src/main/java/com/threeping/mudium/scope/dto/AverageScopeDTO.java
  MUDIUM/src/main/java/com/threeping/mudium/scope/dto/ScopeDTO.java
  MUDIUM/src/main/java/com/threeping/mudium/scope/service/ScopeServiceImpl.java
  MUDIUM/src/main/java/com/threeping/mudium/scope/vo/ScopeVO.java
  MUDIUM/src/test/java/com/threeping/mudium/performance/service/PerformanceServiceImplTests.java
  MUDIUM/src/test/java/com/threeping/mudium/review/service/ReviewServiceTests.java
  MUDIUM/src/test/java/com/threeping/mudium/reviewcomment/service/ReviewCommentServiceImplTests.java
  MUDIUM/src/test/java/com/threeping/mudium/scope/service/ScopeServiceImplTests.java
Labels: feat✨, BackEnd🔙

#100 feat: 커스텀 티켓(이미지) 조회 생성 수정 삭제
  MUDIUM/src/main/java/com/threeping/mudium/customticket/aggregate/dto/CustomTicketDTO.java
  MUDIUM/src/main/java/com/threeping/mudium/customticket/aggregate/dto/UserCustomTicketDTO.java
  MUDIUM/src/main/java/com/threeping/mudium/customticket/aggregate/entity/CustomTicketEntity.java
  MUDIUM/src/main/java/com/threeping/mudium/customticket/aggregate/entity/UserCustomTicketEntity.java
  MUDIUM/src/main/java/com/threeping/mudium/customticket/aggregate/entity/UserCustomTicketId.java
  MUDIUM/src/main/java/com/threeping/mudium/customticket/controller/CustomTicketController.java
  MUDIUM/src/main/java/com/threeping/mudium/customticket/controller/UserCustomTicketController.java
  MUDIUM/src/main/java/com/threeping/mudium/customticket/repository/CustomTicketRepository.java
  MUDIUM/src/main/java/com/threeping/mudium/customticket/repository/UserCustomTicketRepository.java
  MUDIUM/src/main/java/com/threeping/mudium/customticket/service/CustomTicketService.java
  MUDIUM/src/main/java/com/threeping/mudium/customticket/service/CustomTicketServiceImpl.java
  MUDIUM/src/main/java/com/threeping/mudium/customticket/service/UserCustomTicketService.java
  MUDIUM/src/main/java/com/threeping/mudium/customticket/service/UserCustomTicketServiceImpl.java
  MUDIUM/src/main/java/com/threeping/mudium/musical/service/APIServiceImpl.java
  MUDIUM/src/main/java/com/threeping/mudium/performance/service/RankAPIServiceImpl.java
  MUDIUM/src/test/java/com/threeping/mudium/customticket/service/CustomTicketServiceImplTests.java
  MUDIUM/src/test/java/com/threeping/mudium/customticket/service/UserCustomTicketServiceImplTests.java
Labels: feat✨, BackEnd🔙

#102 feat: 커스텀 티켓 삭제
  MUDIUM/src/main/java/com/threeping/mudium/customticket/controller/CustomTicketController.java
  MUDIUM/src/main/java/com/threeping/mudium/customticket/service/CustomTicketServiceImpl.java
  MUDIUM/src/main/java/com/threeping/mudium/performance/service/RankAPIClient.java
Labels: feat✨, BackEnd🔙

#103 feat: 리뷰 좋아요 기능
  MUDIUM/src/main/java/com/threeping/mudium/reviewlike/aggregate/entity/ReviewLike.java
  MUDIUM/src/main/java/com/threeping/mudium/reviewlike/aggregate/entity/ReviewLikePK.java
  MUDIUM/src/main/java/com/threeping/mudium/reviewlike/controller/ReviewLikeController.java
  MUDIUM/src/main/java/com/threeping/mudium/reviewlike/repository/ReviewLikeRepository.java
  MUDIUM/src/main/java/com/threeping/mudium/reviewlike/service/ReviewLikeService.java
  MUDIUM/src/main/java/com/threeping/mudium/reviewlike/service/ReviewLikeServiceImpl.java
  MUDIUM/src/test/java/com/threeping/mudium/reviewlike/service/ReviewLikeServiceTests.java
Labels: feat✨, BackEnd🔙

#104 fix: 주석 삭제
  MUDIUM/src/main/java/com/threeping/mudium/customticket/controller/CustomTicketController.java
Labels: BackEnd🔙, fix🛠️

#105 ADD: API 통신 기능 수정
  .idea/compiler.xml
  MUDIUM/src/main/java/com/threeping/mudium/performance/service/RankAPIServiceImpl.java
Labels: BackEnd🔙, fix🛠️

#106 FIX: 공연 DTO 필드 수정
  MUDIUM/src/main/java/com/threeping/mudium/musical/service/APIServiceImpl.java
  MUDIUM/src/main/java/com/threeping/mudium/musical/service/MusicalAPIClient.java
  MUDIUM/src/main/java/com/threeping/mudium/musical/service/MusicalServiceImpl.java
  MUDIUM/src/main/java/com/threeping/mudium/performance/controller/PerformanceController.java
  MUDIUM/src/main/java/com/threeping/mudium/performance/dto/PerformanceDTO.java
  MUDIUM/src/main/java/com/threeping/mudium/performance/repository/PerformanceRankRepository.java
  MUDIUM/src/main/java/com/threeping/mudium/performance/service/PerformanceServiceImpl.java
  MUDIUM/src/main/java/com/threeping/mudium/review/dto/ReviewWithScopeDTO.java
  MUDIUM/src/main/java/com/threeping/mudium/review/repository/ReviewRepository.java
Labels: BackEnd🔙, fix🛠️

#107 [캘린더] 이미지 경로 인코딩
  MUDIUM/src/main/java/com/threeping/mudium/calendar/aggregate/dto/CalendarDTO.java
  MUDIUM/src/main/java/com/threeping/mudium/calendar/aggregate/entity/CalendarTheme.java
  MUDIUM/src/main/java/com/threeping/mudium/calendar/controller/CalendarController.java
  MUDIUM/src/main/java/com/threeping/mudium/calendar/repository/CalendarRepository.java
  MUDIUM/src/main/java/com/threeping/mudium/calendar/service/CalendarService.java
  MUDIUM/src/main/java/com/threeping/mudium/calendar/service/CalendarServiceImpl.java
  MUDIUM/src/main/resources/calendar/asset/aladdin1.jpg
  MUDIUM/src/main/resources/calendar/asset/aladdin2.jpg
  MUDIUM/src/main/resources/calendar/asset/aladdin3.jpg
  MUDIUM/src/main/resources/calendar/asset/calendar_image_1.png
  MUDIUM/src/main/resources/calendar/asset/calendar_image_2.png
  MUDIUM/src/main/resources/calendar/asset/calendar_image_3.png
  MUDIUM/src/main/resources/calendar/asset/calendar_image_4.png
  MUDIUM/src/main/resources/calendar/asset/lalaland.jpg
  MUDIUM/src/main/resources/calendar/asset/mammamia.jpg
Labels: feat✨, BackEnd🔙, fix🛠️

#109 feat: 리뷰 userId로 조회하는 기능
  MUDIUM/src/main/java/com/threeping/mudium/calendar/entity/CalendarTheme.java
  MUDIUM/src/main/java/com/threeping/mudium/performance/service/RankAPIClient.java
  MUDIUM/src/main/java/com/threeping/mudium/review/controller/ReviewController.java
  MUDIUM/src/main/java/com/threeping/mudium/review/repository/ReviewRepository.java
  MUDIUM/src/main/java/com/threeping/mudium/review/service/ReviewService.java
  MUDIUM/src/main/java/com/threeping/mudium/review/service/ReviewServiceImpl.java
  MUDIUM/src/test/java/com/threeping/mudium/review/service/ReviewServiceTests.java
Labels: feat✨, BackEnd🔙

#114 ScopeTest 코드 수정
  MUDIUM/src/main/java/com/threeping/mudium/musical/service/APIServiceImpl.java
  MUDIUM/src/main/java/com/threeping/mudium/musical/service/YoutubeAPI.java
  MUDIUM/src/main/java/com/threeping/mudium/musical/service/YoutubeService.java
  MUDIUM/src/main/java/com/threeping/mudium/performance/service/RankAPIServiceImpl.java
  MUDIUM/src/test/java/com/threeping/mudium/scope/service/ScopeServiceImplTests.java
Labels: BackEnd🔙, fix🛠️

#115 FIX: performance test 수정
  MUDIUM/src/main/java/com/threeping/mudium/performance/controller/PerformanceController.java
  MUDIUM/src/main/java/com/threeping/mudium/performance/service/PerformanceServiceImpl.java
  MUDIUM/src/main/java/com/threeping/mudium/scope/controller/ScopeController.java
  MUDIUM/src/main/java/com/threeping/mudium/scope/dto/ScopeDTO.java
  MUDIUM/src/main/java/com/threeping/mudium/scope/repository/ScopeRepository.java
  MUDIUM/src/main/java/com/threeping/mudium/scope/service/ScopeService.java
  MUDIUM/src/main/java/com/threeping/mudium/scope/service/ScopeServiceImpl.java
  MUDIUM/src/test/java/com/threeping/mudium/mucialcomment/service/MusicalCommentServiceImplTests.java
  MUDIUM/src/test/java/com/threeping/mudium/musicalreply/service/MusicalReplyServiceImplTests.java
Labels: BackEnd🔙, fix🛠️

#117 feat: 리뷰 수정
  MUDIUM/src/main/java/com/threeping/mudium/musical/service/APIServiceImpl.java
  MUDIUM/src/main/java/com/threeping/mudium/performance/service/RankAPIServiceImpl.java
  MUDIUM/src/main/java/com/threeping/mudium/review/aggregate/entity/Review.java
  MUDIUM/src/main/java/com/threeping/mudium/review/controller/ReviewController.java
  MUDIUM/src/main/java/com/threeping/mudium/review/dto/ReviewWithScopeDTO.java
  MUDIUM/src/main/java/com/threeping/mudium/review/repository/ReviewRepository.java
  MUDIUM/src/main/java/com/threeping/mudium/review/service/ReviewService.java
  MUDIUM/src/main/java/com/threeping/mudium/review/service/ReviewServiceImpl.java
  MUDIUM/src/main/java/com/threeping/mudium/secretreview/dto/SecretReviewResponseDTO.java
  MUDIUM/src/test/java/com/threeping/mudium/review/service/ReviewServiceTests.java
Labels: BackEnd🔙, refactor✂️, fix🛠️
